# Generated by Django 4.2.3 on 2023-08-05 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0009_alter_calculator_timestamp_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 2, 6, 39, 411031, tzinfo=datetime.timezone.utc)),
        ),
    ]
