# Generated by Django 4.2.3 on 2023-08-05 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0011_alter_calculator_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 2, 9, 59, 912403, tzinfo=datetime.timezone.utc)),
        ),
    ]
