# Generated by Django 4.2.3 on 2023-08-05 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlatRate', '0013_alter_calculator_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 17, 21, 32, 811014, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
